CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password BLOB NOT NULL,
    created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX ids_email ON users(email);


CREATE TABLE IF NOT EXISTS apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT (CURRENT_TIMESTAMP)
);
